services:
  db:
    image: bitnami/postgresql
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DATABASES_NAME}
      POSTGRES_USER: ${DATABASES_USER}
      POSTGRES_PASSWORD: ${DATABASES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d DbForPetProject" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - app_network

  celery:
    build: .
    container_name: celery
    command: celery -A pet_project worker --loglevel=INFO
    volumes:
      - celery_data:/app/celery_volumes
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      ENV_SECRET_KEY: ${CONF_SECRET_KEY}
      ENV_DATABASES_ENGINE: ${DATABASES_ENGINE}
      ENV_DATABASES_NAME: ${DATABASES_NAME}
      ENV_DATABASES_USER: ${DATABASES_USER}
      ENV_DATABASES_PASSWORD: ${DATABASES_PASSWORD}
      ENV_DATABASES_HOST: ${DATABASES_HOST}
      ENV_DATABASES_PORT: ${DATABASES_PORT}
      PYTHONUNBUFFERED: 1
      ENV_RABBITMQ_USER: ${RABBITMQ_USER}
      ENV_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    networks:
      - app_network

  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A pet_project beat --loglevel=INFO
    volumes:
      - celery_beat_data:/app/celery_volumes
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      ENV_SECRET_KEY: ${CONF_SECRET_KEY}
      ENV_DATABASES_ENGINE: ${DATABASES_ENGINE}
      ENV_DATABASES_NAME: ${DATABASES_NAME}
      ENV_DATABASES_USER: ${DATABASES_USER}
      ENV_DATABASES_PASSWORD: ${DATABASES_PASSWORD}
      ENV_DATABASES_HOST: ${DATABASES_HOST}
      ENV_DATABASES_PORT: ${DATABASES_PORT}
      PYTHONUNBUFFERED: 1
      ENV_RABBITMQ_USER: ${RABBITMQ_USER}
      ENV_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - app_network

  web:
    build: .
    container_name: pet_project
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "${WEB_APP_PORT}:8000"
    depends_on:
      celery-beat:
        condition: service_started
      celery:
        condition: service_started
      rabbitmq:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      ENV_SECRET_KEY: ${CONF_SECRET_KEY}
      ENV_DATABASES_ENGINE: ${DATABASES_ENGINE}
      ENV_DATABASES_NAME: ${DATABASES_NAME}
      ENV_DATABASES_USER: ${DATABASES_USER}
      ENV_DATABASES_PASSWORD: ${DATABASES_PASSWORD}
      ENV_DATABASES_HOST: ${DATABASES_HOST}
      ENV_DATABASES_PORT: ${DATABASES_PORT}
      PYTHONUNBUFFERED: 1
      ENV_RABBITMQ_USER: ${RABBITMQ_USER}
      ENV_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    networks:
      - app_network

volumes:
  postgres_data:
  redis_data:
  celery_beat_data:
  celery_data:

networks:
  app_network:
    driver: bridge
